services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    environment:
      PORT: "3011"
    networks:
      - traefik-net
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # Service
      - "traefik.http.services.kahier-api.loadbalancer.server.port=3011"

      # HTTPS router only
      - "traefik.http.routers.kahier-api.rule=Host(`api.crm.kahier.com`)"
      - "traefik.http.routers.kahier-api.entrypoints=websecure"
      - "traefik.http.routers.kahier-api.tls=true"
      - "traefik.http.routers.kahier-api.tls.certresolver=myresolver"
      - "traefik.http.routers.kahier-api.service=kahier-api"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    env_file:
      - .env
    environment:
      PORT: "3010"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # Service
      - "traefik.http.services.kahier-crm.loadbalancer.server.port=3010"

      # HTTPS router only
      - "traefik.http.routers.kahier-crm.rule=Host(`crm.kahier.com`)"
      - "traefik.http.routers.kahier-crm.entrypoints=websecure"
      - "traefik.http.routers.kahier-crm.tls=true"
      - "traefik.http.routers.kahier-crm.tls.certresolver=myresolver"
      - "traefik.http.routers.kahier-crm.service=kahier-crm"

networks:
  traefik-net:
    external: true
  app-net:
    external: true
