services:
  gateway:
    build:
      target: depsdev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/gateway/node_modules
      - pnpm-store:/pnpm
    environment:
      NODE_ENV: development
      URL_DEV: "http://localhost:3000,http://127.0.0.1:3000"
    command: ["pnpm", "--dir", "apps/api/gateway", "dev"]

  crm:
    build:
      target: depsdev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/crm/node_modules
      - pnpm-store:/pnpm
    environment:
      NODE_ENV: development
      URL_DEV: "http://localhost:3000,http://127.0.0.1:3000"
      DB_NAME_FILE: "/run/secrets/db_crm_name_dev"
    secrets:
      - db_crm_name_dev
    command:
      - /bin/sh
      - -lc
      - pnpm --dir apps/api/crm db:generate && pnpm --dir apps/api/crm dev

  company:
    build:
      target: depsdev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/company/node_modules
      - pnpm-store:/pnpm
    environment:
      NODE_ENV: development
      URL_DEV: "http://localhost:3000,http://127.0.0.1:3000"
      DB_NAME_FILE: "/run/secrets/db_company_name_dev"
    secrets:
      - db_company_name_dev
    command:
      - /bin/sh
      - -lc
      - pnpm --dir apps/api/company db:generate && pnpm --dir apps/api/company dev

  kahier:
    build:
      target: depsdev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/api/kahier/node_modules
      - pnpm-store:/pnpm
    environment:
      NODE_ENV: development
      URL_DEV: "http://localhost:3000,http://127.0.0.1:3000"
    command: ["pnpm", "--dir", "apps/api/kahier", "dev"]

  client:
    build:
      target: deps
    working_dir: /app/apps/client
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/client/node_modules
      - pnpm-store:/pnpm

    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://localhost:3011"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-net"
      traefik.http.routers.crm-kahier-dev.rule: "Host(`dev.crm.kahier.com`)"
      traefik.http.routers.crm-kahier-dev.entrypoints: "websecure"
      traefik.http.routers.crm-kahier-dev.tls.certresolver: "myresolver"
      traefik.http.routers.crm-kahier-dev.service: "crm-kahier-dev"
      traefik.http.services.crm-kahier-dev.loadbalancer.server.port: "3000"

    command:
      - /bin/sh
      - -lc
      - pnpm dev --hostname 0.0.0.0 --port 3000

volumes:
  pnpm-store:

secrets:
  db_company_name_dev:
    file: ./secrets/company/mariadb_company_name_dev.txt
  db_crm_name_dev:
    file: ./secrets/crm/mariadb_crm_name_dev.txt
