services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    environment:
      PORT: "3011"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # Service
      - "traefik.http.services.api.loadbalancer.server.port=3011"

      # HTTPS router
      - "traefik.http.routers.api-secure.rule=Host(`api.crm.kahier.com`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.api-secure.service=api"

      # HTTP router -> redirect
      - "traefik.http.routers.api.rule=Host(`api.crm.kahier.com`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=api-redirect"
      - "traefik.http.routers.api.service=api"

      - "traefik.http.middlewares.api-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.api-redirect.redirectscheme.permanent=true"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    env_file:
      - .env
    environment:
      PORT: "3010"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # HTTPS
      - "traefik.http.routers.crm-secure.rule=Host(`crm.kahier.com`)"
      - "traefik.http.routers.crm-secure.entrypoints=websecure"
      - "traefik.http.routers.crm-secure.tls=true"
      - "traefik.http.routers.crm-secure.tls.certresolver=myresolver"

      - "traefik.http.services.crm.loadbalancer.server.port=3010"

      # (Optionnel) HTTP -> HTTPS
      - "traefik.http.routers.crm.rule=Host(`crm.kahier.com`)"
      - "traefik.http.routers.crm.entrypoints=web"
      - "traefik.http.routers.crm.middlewares=redirect-to-https"
      
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"


networks:
  traefik-net:
    external: true
