import { describe, expect, it } from "vitest";
import { splitUrls } from "./config.js";

describe("company service URL configuration", () => {
    it.each([
        [undefined, []],
        ["", []],
        ["   ", []],
        ["http://localhost:3000", ["http://localhost:3000"]],
        ["http://localhost:3000/", ["http://localhost:3000"]],
        [" http://localhost:3000/ ", ["http://localhost:3000"]],
        ["http://a.test,https://b.test", ["http://a.test", "https://b.test"]],
        ["http://a.test/, https://b.test/", ["http://a.test", "https://b.test"]],
        ["a,b,c", ["a", "b", "c"]],
        [" a , b , c ", ["a", "b", "c"]],
        [",,,", []],
        ["a,,b", ["a", "b"]],
        ["a, ,b", ["a", "b"]],
        ["/", [""]],
        ["a/", ["a"]],
        ["a//", ["a/"]],
        ["https://one.test/path/", ["https://one.test/path"]],
        ["https://one.test/path//", ["https://one.test/path/"]],
        ["  api.company.local  ", ["api.company.local"]],
        ["http://a.test,", ["http://a.test"]],
        [",http://a.test", ["http://a.test"]],
        ["http://a.test,,https://b.test,", ["http://a.test", "https://b.test"]],
        ["one\ntwo", ["one\ntwo"]],
        ["https://a.test/?x=1/", ["https://a.test/?x=1"]],
        ["ftp://a.test/", ["ftp://a.test"]],
        ["0", ["0"]],
        ["false", ["false"]],
        ["a, b/", ["a", "b"]],
        ["a /, b /", ["a ", "b "]],
        ["a\t,\tb", ["a", "b"]],
        ["  a  ,  b  ,  ", ["a", "b"]],
        ["http://127.0.0.1:3000/", ["http://127.0.0.1:3000"]],
        ["https://company.example.com/", ["https://company.example.com"]],
        ["localhost", ["localhost"]],
        ["localhost/", ["localhost"]],
        ["a,b/", ["a", "b"]],
        ["a//,b//", ["a/", "b/"]],
        ["  ,  ", []],
        ["a,b,c,d", ["a", "b", "c", "d"]],
        ["a, b, c/", ["a", "b", "c"]],
        ["https://a.test///", ["https://a.test//"]],
        ["https://a.test:443/", ["https://a.test:443"]],
        ["http://[::1]:3000/", ["http://[::1]:3000"]],
        ["https://a.test/path?x=/", ["https://a.test/path?x="]],
        ["https://first.test/,https://second.test/", ["https://first.test", "https://second.test"]],
    ])("normalizes %s", (input, expected) => expect(splitUrls(input)).toEqual(expected));
});
